TRAIN:
  ENABLE: False
  DATASET: ava
  BATCH_SIZE: 28
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: "/home/group-cvg/sovan/code_backup/Slowfast/slowfast/models/pretrain/SLOWFAST_32x2_R101_50_50.pkl"
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3, 3]
DETECTION:
  ENABLE: True
  ALIGNED: True
AVA:
#  ANNOTATION_DIR: "/media/datasets/sovan/AVA2/"
#  TRAIN_SCENE: "/media/work/sovan/STDetection/train_cutscenes_labels/"
#  # FRAME_DIR: "/home/sovan/data/short_videos_orig_aspect"
#  # FRAME_LIST_DIR: "/home/sovan/data/"
#  FRAME_DIR: "/home/biswas/data/short_clip"
#  FRAME_LIST_DIR: "/home/biswas/data"
#  DETECTION_SCORE_THRESH: 0.8
  ANNOTATION_DIR: "/media/datasets/sovan/AVA2/"
  TRAIN_SCENE: "/home/group-cvg/sovan/code_backup/STDetection/train_cutscenes_labels/"
  # FRAME_DIR: "/home/sovan/data/short_videos_orig_aspect"
  # FRAME_LIST_DIR: "/home/sovan/data/"
  FRAME_DIR: "/media/data/sovan/AVA_VAL_Videos/frames"
  FRAME_LIST_DIR: "/home/group-cvg/sovan/AVA/data/"
  DETECTION_SCORE_THRESH: 0.0
  TRAIN_GT_BOX_LISTS: ["ava_train_v2.2.csv"]
  TRAIN_PREDICT_BOX_LISTS: ["ava_train_v2.2s_weakly.csv"]
  TEST_PREDICT_BOX_LISTS: ["ava_val_v2.2_weakly.csv"]
  CLIP_DURATION: 1
  PERTURBATION: 0
SLOWFAST:
  ALPHA: 4
  BETA_INV: 8
  FUSION_CONV_CHANNEL_RATIO: 2
  FUSION_KERNEL_SZ: 5
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3, 3], [4, 4], [6, 6], [3, 3]]
  SPATIAL_DILATIONS: [[1, 1], [1, 1], [1, 1], [2, 2]]
  SPATIAL_STRIDES: [[1, 1], [2, 2], [2, 2], [1, 1]]
NONLOCAL:
  LOCATION: [[[], []], [[], []], [[6, 13, 20], []], [[], []]]
  GROUP: [[1, 1], [1, 1], [1, 1], [1, 1]]
  INSTANTIATION: dot_product
  POOL: [[[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]], [[2, 2, 2], [2, 2, 2]]]
BN:
  USE_PRECISE_STATS: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.0375
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 6, 17, 20]
  # STEPS: [0, 9, 10, 11]
  LRS: [1, 0.1, 0.01, 0.001]
  MAX_EPOCH: 10
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-7
  WARMUP_EPOCHS: 3.0
  WARMUP_START_LR: 0.000125
  OPTIMIZING_METHOD: sgd
  # OPTIMIZING_METHOD: adam
MODEL:
  NUM_CLASSES: 80
  ARCH: slowfast
  MODEL_NAME: SlowFast
  LOSS_FUNC: bce
  DROPOUT_RATE: 0.5
  HEAD_ACT: sigmoid
  IS_FULL: False
  UNCERTAINITY: False
  CONTRASTIVE: True
TEST:
  ENABLE: True
  DATASET: ava
  BATCH_SIZE: 1
  CHECKPOINT_FILE_PATH: "/media/work/sovan/WeakContrastSlowfast/WeakBagContrast101_30/checkpoints/checkpoint_epoch_00003.pyth"
DATA_LOADER:
  NUM_WORKERS: 10 
  PIN_MEMORY: True
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: ../WeakBagContrast101_1/
